/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4040052223a0b0f770c16bb3aafa92e0)
interface __BaseEnv_Env {
	LANEDECK_BUCKET: R2Bucket;
	LANEDECK_DB: D1Database;
	ASSETS: Fetcher;
	LANEDECK_AGENT_TOKEN: string;
	LANEDECK_AI_MUTATION_TOKEN: string;
	LANEDECK_READ_TOKEN: string;
	WORKSPACE_COORDINATOR: DurableObjectNamespace<import("./src/index").WorkspaceCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WorkspaceCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
