/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 50aa50494a83e65cabe0fd8c882aabd9)
interface __BaseEnv_Env {
	LANEDECK_BUCKET: R2Bucket;
	LANEDECK_DB: D1Database;
	ASSETS: Fetcher;
	LANEDECK_ACCESS_TEAM_DOMAIN: "https://atticusdeng.cloudflareaccess.com";
	LANEDECK_ACCESS_AUD: "2d0232c963906b4d341a49d85dc65934947f18515cdc1d5de2d50ad643920775";
	LANEDECK_ACCESS_ALLOWED_EMAILS: "atticusdeng@gmail.com";
	LANEDECK_AGENT_TOKEN: string;
	LANEDECK_AI_MUTATION_TOKEN: string;
	LANEDECK_READ_TOKEN: string;
	WORKSPACE_COORDINATOR: DurableObjectNamespace<import("./src/index").WorkspaceCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WorkspaceCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
