/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ab6233757df67a5a9fad9552a92af05f)
interface __BaseEnv_Env {
	LANEDECK_BUCKET: R2Bucket;
	LANEDECK_DB: D1Database;
	ASSETS: Fetcher;
	LANEDECK_AGENT_TOKEN: string;
	LANEDECK_AI_MUTATION_TOKEN: string;
	LANEDECK_READ_TOKEN: string;
	WORKSPACE_COORDINATOR: DurableObjectNamespace<import("./src/index").WorkspaceCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WorkspaceCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LANEDECK_AGENT_TOKEN" | "LANEDECK_AI_MUTATION_TOKEN" | "LANEDECK_READ_TOKEN">> {}
}
